import esbuild from "esbuild";
import process from "node:process";
import { vuePlugin } from "./esbuild-vue-plugin.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/
`;

const isProduction = process.argv[2] === "production";

const ctx = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian"],
  format: "cjs",
  target: "es2018",
  platform: "browser",
  outfile: "main.js",
  sourcemap: isProduction ? false : "inline",
  plugins: [vuePlugin()],
  alias: {
    vue: "vue/dist/vue.runtime.esm-bundler.js",
  },
});

if (isProduction) {
  await ctx.rebuild();
  await ctx.dispose();
} else {
  await ctx.watch();
}
